-- Drop all tables to ensure no errors;

DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS "PLAN";
DROP TABLE IF EXISTS "PROPERTY";
DROP TABLE IF EXISTS "PROP_AMORT";
DROP TABLE IF EXISTS "PLAN_AMORT";

-- User table is to contain multiple plans

CREATE TABLE "USER" (
	U_ID VARCHAR(50) NOT NULL,
	U_ID_CREATED DATE NOT NULL DEFAULT NOW(),
	U_PASSWORD VARCHAR(50) NOT NULL,

	-- EXTRAS
	CUSTOM1 VARCHAR(50),
	CUSTOM2 VARCHAR(50),
	CUSTOM3 VARCHAR(50),
	CUSTOM4 VARCHAR(50),
	CUSTOM5 VARCHAR(50),
	CUSTOM6 VARCHAR(50),
	CUSTOM7 VARCHAR(50),
	CUSTOM8 VARCHAR(50),
	CUSTOM9 VARCHAR(50),
	CUSTOM0 VARCHAR(50),

	PRIMARY KEY (U_ID)
);

-- Plan table is to contain multiple properties

CREATE TABLE "PLAN" (
	-- APP DATA
	PL_ID VARCHAR(50) NOT NULL, -- User Created Plan ID 
	PL_ID_CREATED DATE NOT NULL DEFAULT NOW(),
	U_ID VARCHAR(50) NOT NULL,

	-- PLAN DATA
	PLAN_LENGTH_YEAR VARCHAR(50),
	PLAN_LENGTH_MONTH VARCHAR(50),
	PLAN_LENGTH_DAY VARCHAR(50),
	PLAN_INITIAL_CASH VARCHAR(50),
	PLAN_INITIAL_INVEST VARCHAR(50),
	SALARY_YEAR VARCHAR(50),
	BONUS_PERC_SALARY_YEAR VARCHAR(50),
	BONUS_FREQ_YEAR VARCHAR(50),
	MARKET_RATE_YEAR VARCHAR(50),
	INCOME_TAX_RATE_YEAR VARCHAR(50),
	DONATIONS_PERC_SALARY_YEAR VARCHAR(50),
	DONATIONS_FREQ_YEAR VARCHAR(50),
	INFLATION_RATE_YEAR VARCHAR(50),

	-- MIGHT NOT USE
	CASH_ON_HAND VARCHAR(50),
	SAVE_ABOVE_CASH_ON_HAND VARCHAR(50),

	-- EXTRAS
	CUSTOM1 VARCHAR(50),
	CUSTOM2 VARCHAR(50),
	CUSTOM3 VARCHAR(50),
	CUSTOM4 VARCHAR(50),
	CUSTOM5 VARCHAR(50),
	CUSTOM6 VARCHAR(50),
	CUSTOM7 VARCHAR(50),
	CUSTOM8 VARCHAR(50),
	CUSTOM9 VARCHAR(50),
	CUSTOM0 VARCHAR(50),

	PRIMARY KEY (PL_ID, U_ID)
);

-- Property table is to contain all information to configure and calculate amortization schedule for a loan

CREATE TABLE "PROPERTY" (
	-- APP DATA
	U_ID VARCHAR(50) NOT NULL,
	PL_ID VARCHAR(50) NOT NULL, -- User Created Plan ID 
	P_ID VARCHAR(50) NOT NULL, -- User Created Property ID 
	P_ID_CREATED DATE NOT NULL DEFAULT NOW(),

	-- LOAN DATA
	PROPERTY_PRICE VARCHAR(50),
	LOAN_DOWNPAY VARCHAR(30),
	LOAN_AMOUNT VARCHAR(50), -- Calculated
	LOAN_START_DATE DATE,
	LOAN_LENGTH_YEAR VARCHAR(50), 
	LOAN_END_DATE DATE, -- Calculated
	LOAN_LENGTH_MONTH VARCHAR(50),  -- Calculated
	LOAN_LENGTH_DAY VARCHAR(50),  -- Calculated
	LOAN_PAY_FREQ_YEAR VARCHAR(50),
	LOAN_INT_RATE_YEAR VARCHAR(30),
	LOAN_LENDER_CRED VARCHAR(50),
	LOAN_ORIG_COSTS VARCHAR(50),
	LOAN_PERIODIC_PAY VARCHAR(50), -- Calculated with equation PeriodicPayment
	
	-- PERIODIC VALUES/COSTS
	RENT_YES_NO VARCHAR(50),
	OWN_YES_NO VARCHAR(50),
	RENT_START_DATE VARCHAR(50),
	RENT_END_DATE VARCHAR(50),
	RENT_FREQ_YEAR VARCHAR(50),
	RENT_PRICE VARCHAR(50),
	COUNTY_TAX_YEAR VARCHAR(50),
	SCHOOL_TAX_YEAR VARCHAR(50),
	MUD_TAX_YEAR VARCHAR(50),
	HOA_FEES_YEAR VARCHAR(50),
	HOMEOWN_INSURE_YEAR VARCHAR(50),
	FLOOD_INSURE_YEAR VARCHAR(50),
	MORTGAGE_INSURE_YES_NO VARCHAR(50),
	MORTGAGE_INSURE_RATE_YEAR VARCHAR(50),
	TITLE_INSURE_YES_NO VARCHAR(50),
	TITLE_INSURE_YEAR VARCHAR(50),
	HOMESTEAD_EXEMPT_YES_NO VARCHAR(50),
	HOMESTEAD_EXEMPT_YEAR VARCHAR(50),
	HOME_APPREC_RATE_YEAR VARCHAR(50),
	SECURITY_SYSTEM_YES_NO VARCHAR(50),
	SECURITY_SYSTEM_START_DATE VARCHAR(50),
	SECURITY_SYSTEM_END_DATE VARCHAR(50),
	SECURITY_SYSTEM_FREQ_YEAR VARCHAR(50),
	SECURITY_SYSTEM_PRICE VARCHAR(50),
	LANDSCAPE_YES_NO VARCHAR(50),
	LANDSCAPE_START_DATE VARCHAR(50),
	LANDSCAPE_END_DATE VARCHAR(50),
	LANDSCAPE_FREQ_YEAR VARCHAR(50),
	LANDSCAPE_PRICE VARCHAR(50),
	BUG_YES_NO VARCHAR(50),
	BUG_START_DATE VARCHAR(50),
	BUG_END_DATE VARCHAR(50),
	BUG_FREQ_YEAR VARCHAR(50),
	BUG_PRICE VARCHAR(50),
	SOLAR_YES_NO VARCHAR(50),
	SOLAR_START_DATE VARCHAR(50),
	SOLAR_END_DATE VARCHAR(50),
	SOLAR_FREQ_YEAR VARCHAR(50),
	SOLAR_PRICE VARCHAR(50),
	SOLAR_SAVINGS VARCHAR(50),
	PROPERTY_MAN_YES_NO VARCHAR(50),
	PROPERTY_MAN_START_DATE VARCHAR(50),
	PROPERTY_END_DATE VARCHAR(50),
	PROPERTY_MAN_FREQ_YEAR VARCHAR(50),
	PROPERTY_MAN_PRICE VARCHAR(50),
	HOME_AVG_ENERGY_FREQ_YEAR VARCHAR(50),
	HOME_AVG_ENERGY_PRICE VARCHAR(50),
	ESCROW_YES_NO VARCHAR(50),
	
	-- EXTRA AND 1-TIME COSTS
	INSPECTION_FEES VARCHAR(50),
	HOME_WARRANTIES VARCHAR(50),
	TITLE_CO_CLOSING_COSTS VARCHAR(50),
	REALTOR_BUY_FEE_RATE VARCHAR(50),
	REALTOR_SELL_FEE_RATE VARCHAR(50),
	REALTOR_FEES_PERIODIC VARCHAR(50),

	-- MIGHT NOT USE
	CUSTOM_EXT_PAY_YES_NO VARCHAR(50),
	CUSTOM_EXT_PAY VARCHAR(50),
	FIXED_EXT_PAY_YES_NO VARCHAR(50),
	FIXED_EXT_PAY_FREQ_YEAR VARCHAR(50),
	FIXED_EXT_PAY_PRICE VARCHAR(50),

	-- EXTRAS
	CUSTOM1 VARCHAR(50),
	CUSTOM2 VARCHAR(50),
	CUSTOM3 VARCHAR(50),
	CUSTOM4 VARCHAR(50),
	CUSTOM5 VARCHAR(50),
	CUSTOM6 VARCHAR(50),
	CUSTOM7 VARCHAR(50),
	CUSTOM8 VARCHAR(50),
	CUSTOM9 VARCHAR(50),
	CUSTOM0 VARCHAR(50),
	
	PRIMARY KEY (U_ID, PL_ID, P_ID)
);

-- Prop_amort table is to hold the amortization calculation generated by a configured property

CREATE TABLE "PROP_AMORT" (
	U_ID VARCHAR(50) NOT NULL,
	PL_ID VARCHAR(50) NOT NULL, -- User Created Plan ID 
	P_ID VARCHAR(50) NOT NULL, -- User Created Property ID 
	PRA_TIMESTAMP TIMESTAMP NOT NULL,
	MONEY_AMOUNT VARCHAR(50),
	CONSTRAINT attributes_pk PRIMARY KEY (U_ID, PL_ID, P_ID,PRA_TIMESTAMP)
);

-- Plan_amort table is to hold the amortization calculation of multiple configured properties

CREATE TABLE "PLAN_AMORT" (
	U_ID VARCHAR(50) NOT NULL,
	PL_ID VARCHAR(50) NOT NULL, -- User Created Plan ID 
	P_ID VARCHAR(50) NOT NULL, -- User Created Property ID 
	PLA_TIMESTAMP TIMESTAMP NOT NULL,
	MONEY_AMOUNT VARCHAR(50),
	PRIMARY KEY (U_ID, PL_ID, P_ID, PLA_TIMESTAMP)
);

CREATE TABLE "CUSTOM_PAY" (
	U_ID VARCHAR(50) NOT NULL,
	PL_ID VARCHAR(50) NOT NULL, -- User Created Plan ID 
	P_ID VARCHAR(50) NOT NULL, -- User Created Property ID 
	PA_TIMESTAMP TIMESTAMP NOT NULL,
	MONEY_AMOUNT VARCHAR(50),
	PRIMARY KEY (U_ID, PL_ID, P_ID, PLA_TIMESTAMP)
);


'''
-----------------------------------  SAMPLE DATA  -------------------------------------

'''


# defining data from user about user #1
u_id = 'user_1'
u_id_created = dt.date.today()
u_password = 'password123'


# defining data from user about plan #1
pl_id = 'my_first_plan'
pl_id_created = dt.date.today()
u_id = u_id
plan_length_year = 50
plan_length_month = plan_length_year*12
plan_length_day = plan_length_year*365
plan_initial_cash = 50000
plan_initial_invest = 25000
salary_year = 75000
bonus_perc_salary_year = 5
bonus_freq_year = 1
market_rate_year = 9
income_tax_rate_year = 15
donations_perc_year = 10
donations_freq_year = 24
inflation_rate_year = 3

cash_on_hand = .5*salary_year
save_above_cash_on_hand = True 


# defining data from user about property #1
u_id = u_id
pl_id = pl_id
p_id = 'my_first_property'
pi_created = dt.date.today()

property_price = 250000
loan_downpay = 50000
loan_amount = property_price - loan_downpay
loan_start_date = dt.date.today()
loan_length_year = 30
loan_end_date = loan_start_date + dt.timedelta(days=365*loan_length_year)
loan_length_month = loan_length_year*12
loan_length_day = (loan_start_date - loan_end_date).days
loan_pay_freq_year = 12
loan_int_rate_year = .04
loan_lender_cred = 0
loan_orig_costs = 0
escrow_yes_no = True

rent_yes_no = True
own_yes_no = False
rent_freq_year = 12
rent_price = 2000
county_tax_year = .01
school_tax_year = .01
mud_tax_year = .01
hoa_fees_year = 1500
homeown_insure_year = 1500
flood_insure_year = 750
mortgage_insure_yes_no = False
mortgage_insure_rate_year = 0
title_insure_yes_no = True
title_insure_year = 500
homestead_exempt_yes_no = True
homestead_exempt_year = 2000
home_apprec_rate_year = .02
security_system_yes_no = True
security_system_freq_year = 12
security_system_price = 75
landscape_yes_no = False
landscape_freq_year = 12
landscape_price = 50
bug_yes_no = True
bug_freq_year = 4
bug_price = 100
solar_yes_no = True
solar_freq_year = 12
solar_price = 115
solar_savings = 80
property_manage_yes_no = True
property_man_freq_year = 12
property_man_price = 200
home_avg_energy_freq_year = 12
home_avg_energy_price = 200

inspection_fees = 800
home_warranties = 2000
title_co_closing_costs = 2000
realtor_buy_fee_rate = .03*property_price
realtor_sell_fee_rate = .03*property_price
realtor_fees_periodic = 0

custom_ext_pay_yes_no = False
custom_ext_pay = []
fixed_ext_pay_yes_no = False
fixed_ext_pay_freq_year = 12
fixed_ext_pay_price = 100

test_user_object = {
    'u_id':u_id,
    'u_id_created':u_id_created,
    'u_password':u_password
}
test_plan_object = {
    'pl_id':pl_id,
    'pl_id_created':pl_id_created,
    'u_id':u_id,
    'plan_length_year':plan_length_year,
    'plan_length_month':plan_length_month,
    'plan_length_day':plan_length_day,
    'plan_initial_cash':plan_initial_cash,
    'plan_initial_invest':plan_initial_invest,
    'salary_year':salary_year,
    'bonus_perc_salary_year':bonus_perc_salary_year,
    'bonus_freq_year':bonus_freq_year,
    'market_rate_year':market_rate_year,
    'income_tax_rate_year':income_tax_rate_year,
    'donations_perc_year':donations_perc_year,
    'donations_freq_year':donations_freq_year,
    'inflation_rate_year':inflation_rate_year,
    'cash_on_hand':cash_on_hand,
    'save_above_cash_on_hand':save_above_cash_on_hand
}
test_property_object = {
    'u_id':u_id,
    'pl_id':pl_id,
    'p_id':p_id,
    'pi_created':pi_created,
    'property_price':property_price,
    'loan_downpay':loan_downpay,
    'loan_amount':loan_amount,
    'loan_start_date':loan_start_date,
    'loan_length_year':loan_length_year,
    'loan_end_date':loan_end_date,
    'loan_length_month':loan_length_month,
    'loan_length_day':loan_length_day,
    'loan_pay_freq_year':loan_pay_freq_year,
    'loan_int_rate_year':loan_int_rate_year,
    'loan_lender_cred':loan_lender_cred,
    'loan_orig_costs':loan_orig_costs,
    'escrow_yes_no':escrow_yes_no,
    'rent_yes_no':rent_yes_no,
    'own_yes_no':own_yes_no,
    'rent_freq_year':rent_freq_year,
    'rent_price':rent_price,
    'county_tax_year':county_tax_year,
    'school_tax_year':school_tax_year,
    'mud_tax_year':mud_tax_year,
    'hoa_fees_year':hoa_fees_year,
    'homeown_insure_year':homeown_insure_year,
    'flood_insure_year':flood_insure_year,
    'mortgage_insure_yes_no':mortgage_insure_yes_no,
    'mortgage_insure_rate_year':mortgage_insure_rate_year,
    'title_insure_yes_no':title_insure_yes_no,
    'title_insure_year':title_insure_year,
    'homestead_exempt_yes_no':homestead_exempt_yes_no,
    'homestead_exempt_year':homestead_exempt_year,
    'home_apprec_rate_year':home_apprec_rate_year,
    'security_system_yes_no':security_system_yes_no,
    'security_system_freq_year':security_system_freq_year,
    'security_system_price':security_system_price,
    'landscape_yes_no':landscape_yes_no,
    'landscape_freq_year':landscape_freq_year,
    'landscape_price':landscape_price,
    'bug_yes_no':bug_yes_no,
    'bug_freq_year':bug_freq_year,
    'bug_price':bug_price,
    'solar_yes_no':solar_yes_no,
    'solar_freq_year':solar_freq_year,
    'solar_price':solar_price,
    'solar_savings':solar_savings,
    'property_manage_yes_no':property_manage_yes_no,
    'property_man_freq_year':property_man_freq_year,
    'property_man_price':property_man_price,
    'home_avg_energy_freq_year':home_avg_energy_freq_year,
    'home_avg_energy_price':home_avg_energy_price,
    'inspection_fees':inspection_fees,
    'home_warranties':home_warranties,
    'title_co_closing_costs':title_co_closing_costs,
    'realtor_buy_fee_rate':realtor_buy_fee_rate,
    'realtor_sell_fee_rate':realtor_sell_fee_rate,
    'realtor_fees_periodic':realtor_fees_periodic,
    'custom_ext_pay_yes_no':custom_ext_pay_yes_no,
    'custom_ext_pay':custom_ext_pay,
    'fixed_ext_pay_yes_no':fixed_ext_pay_yes_no,
    'fixed_ext_pay_freq_year':fixed_ext_pay_freq_year,
    'fixed_ext_pay_price':fixed_ext_pay_price
}